const ordersKey = 'shree-devi-orders';
const adminTokenKey = 'shree-devi-admin-token';
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;
const readOrders = () => { try { return JSON.parse(localStorage.getItem(ordersKey) || '[]'); } catch { return []; } };
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
let orders = readOrders();
function render(){
  const query = document.querySelector('#order-search').value.trim().toLowerCase();
  const visible = orders.filter(order => `${order.orderNumber} ${order.customer?.name} ${order.customer?.phone} ${order.customer?.city}`.toLowerCase().includes(query));
  document.querySelector('#metric-orders').textContent = orders.length;
  document.querySelector('#metric-sales').textContent = money(orders.reduce((sum, order) => sum + Number(order.total || 0), 0));
  document.querySelector('#metric-qr').textContent = orders.filter(order => order.payment === 'QR payment').length;
  document.querySelector('#metric-cod').textContent = orders.filter(order => order.payment === 'Cash on Delivery').length;
  const body = document.querySelector('#orders-body');
  if (!visible.length) { body.innerHTML = '<tr><td colspan="8" class="empty-state">No matching orders found.</td></tr>'; return; }
  body.innerHTML = visible.slice().reverse().map((order, index) => { const customer = order.customer || {}; const date = order.createdAt ? new Date(order.createdAt).toLocaleString('en-NP',{dateStyle:'medium',timeStyle:'short'}) : '—'; const items = (order.items || []).map(item => `${escapeHtml(item.name)} × ${item.qty}`).join('<br>') || '—'; const transaction = order.transactionCode ? `<span class="status-note">Txn: ${escapeHtml(order.transactionCode)}</span>` : ''; return `<tr><td><span class="order-id">${escapeHtml(order.orderNumber)}</span></td><td><span class="customer-name">${escapeHtml(customer.name)}</span><span class="muted">${escapeHtml(customer.phone)}</span><span class="muted">${escapeHtml(customer.email || '')}</span></td><td>${items}</td><td><strong>${escapeHtml(customer.city)}</strong><span class="muted">${escapeHtml(customer.street || '')}</span><span class="muted">${escapeHtml(customer.address || '')}</span></td><td><span class="payment-badge ${order.payment === 'Cash on Delivery' ? 'cod' : ''}">${escapeHtml(order.payment || '—')}</span>${transaction}</td><td><strong>${money(order.total)}</strong></td><td>${escapeHtml(date)}</td><td><button class="view-order" data-order-index="${orders.indexOf(order)}">View all</button></td></tr>`; }).join('');
  body.querySelectorAll('.view-order').forEach(button => button.addEventListener('click', () => showOrder(orders[Number(button.dataset.orderIndex)])));
}
function showOrder(order){ const modal = document.querySelector('#order-modal'); const detail = document.querySelector('#order-detail'); const customer = order.customer || {}; const items = (order.items || []).map(item => `<div><strong>${escapeHtml(item.name)} × ${item.qty}</strong><span class="muted">${escapeHtml(item.detail || '')}</span></div>`).join('') || '—'; const media = []; if (order.paymentProof) media.push(`<figure><img src="${order.paymentProof}" alt="Payment screenshot" /><figcaption>Payment screenshot</figcaption></figure>`); (order.items || []).forEach(item => { if (item.customImage) media.push(`<figure><img src="${item.customImage}" alt="Customized customer image" /><figcaption>Customized image · ${escapeHtml(item.name)}</figcaption></figure>`); }); detail.innerHTML = `<div class="detail-heading"><p class="eyebrow">ORDER DETAILS</p><h2>${escapeHtml(order.orderNumber)}</h2></div><div class="detail-grid"><div class="detail-card"><b>Customer</b>${escapeHtml(customer.name)}<span class="muted">${escapeHtml(customer.phone)}</span><span class="muted">${escapeHtml(customer.email || 'No email')}</span></div><div class="detail-card"><b>Payment</b>${escapeHtml(order.payment || '—')}<span class="muted">Transaction code: ${escapeHtml(order.transactionCode || 'Not provided')}</span></div><div class="detail-card"><b>Delivery</b>${escapeHtml(customer.city)} · ${escapeHtml(customer.street || '')}<span class="muted">${escapeHtml(customer.address || '')}</span></div><div class="detail-card"><b>Order total</b>${money(order.total)}<span class="muted">${order.createdAt ? new Date(order.createdAt).toLocaleString('en-NP') : '—'}</span></div></div><div class="detail-card" style="margin-top:10px"><b>Items</b>${items}</div>${media.length ? `<div class="order-media">${media.join('')}</div>` : '<p class="muted">No uploaded images attached to this order.</p>'}`; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
function closeOrder(){ const modal = document.querySelector('#order-modal'); modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }
document.querySelector('#order-modal-close').addEventListener('click', closeOrder);
document.querySelector('#order-modal').addEventListener('click', event => { if (event.target.id === 'order-modal') closeOrder(); });
document.querySelector('#order-search').addEventListener('input', render);
function showLogin(show = true){ const login = document.querySelector('#admin-login'); const main = document.querySelector('.dashboard-wrap'); login.hidden = !show; login.setAttribute('aria-hidden', String(!show)); main.hidden = show; }
async function loadOrders(){ try { const firebase = await window.shreeFirebaseReady; const snapshot = await firebase.getDocs(firebase.query(firebase.collection(firebase.db, 'orders'), firebase.orderBy('createdAt', 'desc'))); orders = snapshot.docs.map(item => item.data()); showLogin(false); render(); return; } catch (error) { console.warn('Firebase orders unavailable; trying the local/server fallback.', error); } try { const token = localStorage.getItem(adminTokenKey) || ''; const response = await fetch('/api/orders', {cache:'no-store', headers: token ? {'X-Admin-Token': token} : {}}); if (response.status === 401) { showLogin(true); return; } if (!response.ok) throw new Error('Order API unavailable'); const data = await response.json(); orders = data.orders || []; showLogin(false); render(); } catch { orders = readOrders(); showLogin(false); render(); } }
document.querySelector('#admin-login-form').addEventListener('submit', async event => { event.preventDefault(); const token = document.querySelector('#admin-token').value.trim(); localStorage.setItem(adminTokenKey, token); document.querySelector('#login-message').textContent = 'Checking token…'; await loadOrders(); if (!document.querySelector('#admin-login').hidden) { document.querySelector('#login-message').textContent = 'That token was not accepted.'; localStorage.removeItem(adminTokenKey); } });
document.querySelector('#refresh-orders').addEventListener('click', loadOrders);
document.querySelector('#export-orders').addEventListener('click', () => { const headers = ['Order','Date','Customer','Phone','City','Street','Payment','Total','Items']; const rows = orders.map(order => { const c = order.customer || {}; return [order.orderNumber,order.createdAt,c.name,c.phone,c.city,c.street,order.payment,order.total,(order.items || []).map(item => `${item.name} x${item.qty}`).join(' | ')].map(value => `"${String(value ?? '').replace(/"/g,'""')}"`).join(','); }); const blob = new Blob([[headers.join(','),...rows].join('\n')], {type:'text/csv;charset=utf-8'}); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'shree-devi-orders.csv'; link.click(); URL.revokeObjectURL(link.href); });
loadOrders();
setInterval(loadOrders, 15000);
